name: quick_settings_tile_plugin_platform_interface
version: 0.0.1
description: Platform interface for quick_settings_tile_plugin.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
